name: catalogue_mouches
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  event_bus: '>=0.4.1 <0.5.0'
  slugify: '>=0.1.1 <0.2.0'
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
   - lib/assets/caddis_real.jpg
   - lib/assets/minnows.jpg
   - lib/assets/sangsue_eau.jpg
   - lib/assets/green_drake_nymph.jpg
   - lib/assets/stonefly_nymph_real.jpg
   - lib/assets/copper_john/chenille.png
   - lib/assets/copper_john/copper_wire.png
   - lib/assets/copper_john/end_result.png
   - lib/assets/copper_john/hackle.png
   - lib/assets/copper_john/rubber_legs.png
   - lib/assets/copper_john/parts/bead_gold_1_8.png
   - lib/assets/copper_john/parts/copper_wire_medium.png
   - lib/assets/copper_john/parts/crystal_chenille.png
   - lib/assets/copper_john/parts/rubber_legs_olive.png
   - lib/assets/copper_john/parts/tinsel_flash_back.png
   - lib/assets/copper_john/parts/nymph_hook.png
   - lib/assets/muddler_minnow/end_result.png
   - lib/assets/elk_hair_caddis/end_result.png
   - lib/assets/mickey_finn/end_result.png
   - lib/assets/mickey_bad/end_result.png
   - lib/assets/adams/end_result.png
   - lib/assets/mudlapin/end_result.png
   - lib/assets/woolly_bugger/end_result.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
